version: '3'

services:
  api:
    image: 'carent-backend'
    build: ./carent_backend
    container_name: app
    depends_on:
      - db
    ports:
      - 8085:8085
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/carent

  db:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_DB=carent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
